version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/webapps
    ports:
      - "8001:8001"
    links:
      - db
    depends_on:
      - db
